batch_size: 16
seed: 12345678
lr: 0.001
optimizer: "SGD"
model_name: "network.PACRNN.OCR"
drrn_layers: 5
text_folder: "./res/txt_bak"
bg_folder: "./res/bg_img"
font_folder: "./res/fonts"
vocab_list: "./out/vocab.list"
train_length: 20000
val_length: 2000
ckpt_folder: "./out/model"
log_dir: "./out/log"
display_freq: 10
val_freq: 100
epochs: 10
in_channels: 1
out_channels: 1
nf: 64
unf: 128
nb: 2
nh: 256
num_classes: 4131
scale: 4
ocr_attention: 1
sr_attention: 1
